apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  labels:
    app: details
  annotations:
    dev.nocalhost: |
      containers:
        - dev:
            gitUrl: https://e.coding.net/nocalhost/nocalhost/bookinfo-details.git
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/ruby:2.7-buster
            shell: bash
            workDir: /home/nocalhost-dev
            command:
              run:
                - ./run.sh
              debug:
                - ./debug.sh
            debug:
              remoteDebugPort: 9001
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
                - ".github"
            env: 
            - name: DEBUG
              value: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: nocalhost-docker.pkg.coding.net/nocalhost/bookinfo/details
        imagePullPolicy: IfNotPresent
        command: ['ruby', 'details.rb', '9080']
        ports:
        - containerPort: 9080
        readinessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 32Mi
      - name: ubuntu
        image: nocalhost-docker.pkg.coding.net/nocalhost/public/ubuntu:stable
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', 'tail -f /dev/null']
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 32Mi
---
