- name: details
  serviceType: deployment
  containers:
    - install:
        env:
          - name: ENV_INJECT_EXAM
            value: ANNOTATIONS
      dev:
        gitUrl: https://e.coding.net/nocalhost/nocalhost/bookinfo-details.git
        image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/ruby:2.7-buster
        shell: bash
        workDir: /home/nocalhost-dev
        sync:
          type: send
          filePattern:
            - ./
          ignoreFilePattern:
            - ".git"
            - ".github"
        command:
          run:
            - ./run.sh
          debug:
            - ./debug.sh
        debug:
          remoteDebugPort: 9001